# Generated by Django 4.1.3 on 2022-11-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
